### ISSUE TITLE
blacklist `/drag` at certain locations

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1023]
like heist doors to prevent people from dragging each other thru doors instead of interacting with them properly

can be used to escape jail ?

**Comment by minipunch** [comment]
@ChangyBoi @DatBoiWeep did we do this yet

**Comment by DatBoiWeep** [comment]
> @ChangyBoi @DatBoiWeep did we do this yet

Just for the prison right now

**Comment by minipunch** [comment]
gonna close this for now until we have more specific places in mind
