### ISSUE TITLE
add rcore guide thing

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1038]
see players / staff can add helpful guides for things like

- [ ] spawn zones, explaining stuff in more detail like how to get cell phone, make money, customize char (more so that /info already does perhaps)
- [ ] job sites (explain how to do the job)

and more

**Comment by minipunch** [comment]
depends on MySQL and is encrypted so not easily convertible to Couch DB

going to try to set up MySQL DB alongside Couch DB so it still works...

**Comment by minipunch** [comment]
mysql seems good now, had to:

- [ ] install mysql server
- [ ] create user
- [ ] create database (e.g. named "fivem")
- [ ] install mysql-async resource
- [ ] run rcore_guidebook .sql script once manually
- [ ] going to want to think about hiding the mysql connection string somehow from being on .git, but keeping the server.cfg there

**Comment by minipunch** [comment]
it won't open for me and there is this error in F8 console:

https://forum.cfx.re/t/standalone-in-game-guidebook/4842251/11?u=minipunch

**Comment by minipunch** [comment]
@Savage912-Official  was gonna do this

**Comment by minipunch** [comment]
> "For the rcore_guidebook issue maybe look for any other scripts that call DisableControlAction for the hotkeys
That was literally the issue I just had for the farm property menu 
It was conflicting with usa_holster because that was calling DisableControlAction on the same hotkey for some reason
z in this case"

**Comment by Savage912-Official** [comment]
Attempted the above actions a while back but the current issue is it's not registering the permissions when attempting to open the guide. It should allow anyone to open it but it says no permissions in the discord logs when attempting to open it.

**Comment by minipunch** [comment]
author just released an update title 'fix open event'...

so let's hope that fixes our issue with opening it lol...

going to DL it and let @Savage912-Official try again
