### ISSUE TITLE
no limit on business purchasing

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1055]
currently anyone can "own all the businesses" and people get upset that it is not fair

so for now let's add a limit like we do with residential properties

**Comment by DatBoiWeep** [comment]
wack

**Comment by minipunch** [comment]
![](https://c.tenor.com/cJ9V22mZIG0AAAAC/do-it-just-do-it.gif)

**Comment by Savage912-Official** [comment]
Should be good to be closed? According to @DatBoiWeep there is no limit.

**Comment by DatBoiWeep** [comment]
> Should be good to be closed? According to @DatBoiWeep there is no limit.

Yeah. Nothing that I could see at least.

**Comment by minipunch** [comment]
Lmao this is an ISSUE you guys OKAY

Which means of course there is no limit

THAT'S THE ISSUE !!!!

**Comment by minipunch** [comment]
![](https://c.tenor.com/ZFc20z8DItkAAAAd/facepalm-really.gif)

**Comment by maxgestic** [comment]
This is closed @minipunch
