### ISSUE TITLE
Emotes keybinded repeat without action

### ISSUE THREAD

**Issue by DatBoiWeep** [minipunch/usarealismrp-fxserver#1089]
**Desc**
When you assign the emotes you want to your desired keys; Clicking one keybind will take some time to actually emote, then will continue to emote repeatedly ALL emotes keybinded.

**Steps to Reproduce**
1. Keybind emotes
2. Press desired keybind to emote
3. Wait a few seconds (~5 seconds)
4. Walk/run around and you will continuously emote
5. (To repeat) Continue to walk/run around and you will continue to do all keybinded emotes in random order

**Reference Clip**
https://cdn.discordapp.com/attachments/354307815172734976/999269099769167943/Discord_sBHyAkTJP7.gif

**Tested by @ChangyBoi **

**Comment by minipunch** [comment]
We sure this is repeatable ?

I tried but it works fine for me

These are the binding emotes I had: ![](https://i.imgur.com/AeswInX.png)

**Comment by minipunch** [comment]
was because they rebound their heli flying keys from numpad to WASD so it was conflicting

I added a /togglebinds command
