### ISSUE TITLE
try fire script

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1105]
https://tox-scripts.tebex.io/package/4838366

**Comment by minipunch** [comment]
@Savage912-Official plz reply so I can assign u since u r going to try it out

**Comment by Savage912-Official** [comment]
Testing

**Comment by Crownapple** [comment]
sheeeesh

**Comment by Savage912-Official** [comment]
**Current Issue:**
- It seems the job is not being registered when getting attempting to get the hose.
- No errors have been displayed as of yet.

Branch: https://github.com/Savage912-Official/usarealismrp-fxserver/tree/fire-script

**Comment by minipunch** [comment]
tried it but no 3d text appeared for some reason

and no errors

maybe i can try a fresh copy of the script and see if that at least works for me

**Comment by Savage912-Official** [comment]
Gonna start with a fresh install in the morning.

**Comment by minipunch** [comment]
@maxgestic or @DatBoiWeep think 1 of u guys can help savage get this working ?

**Comment by maxgestic** [comment]
I can give it a try I spose

**Comment by minipunch** [comment]
> I can give it a try I spose

Please do!!

It looks like a solid script assuming it all syncs well on live ultimately which from the vids and description it looks like it should

And then ideally we just generate some random fire calls for EMS to respond to

And eventually it would be cool if players could start fires themselves for arson RP stuff

**Comment by minipunch** [comment]
max added it !
