### ISSUE TITLE
make sure unbanning works with new admin menu

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1177]
`erp_adminmenu`'s unbanning seems to not be working

we enter the ban ID but the ban record is not deleted automatically

- [x] make sure manually unbanning works
- [x] make sure automated temp ban unbanning works

**Comment by minipunch** [comment]
@Savage912-Official ^^

If u can check that out that would be good

I can also look

**Comment by minipunch** [comment]
💯 🥇

**Comment by minipunch** [comment]
Did u also make sure the automated temp unbanning works too lol

Like by banning urself for a few seconds/minutes and rejoining and seeing that u actually do get unbanned in the right time @Savage912-Official

**Comment by Savage912-Official** [comment]
> Did u also make sure the automated temp unbanning works too lol
> 
> Like by banning urself for a few seconds/minutes and rejoining and seeing that u actually do get unbanned in the right time @Savage912-Official

I did and it works as well

**Comment by minipunch** [comment]
Ok nice
