### ISSUE TITLE
NPC and Property Property Card Adjustment

### ISSUE THREAD

**Issue by maxgestic** [minipunch/usarealismrp-fxserver#1185]
As mentioned https://github.com/minipunch/usarealismrp-fxserver/pull/1184#discussion_r960123106 make it so that the chance for a card is just done though one entry and then if that is chosen then pick from the card pool

**Comment by minipunch** [comment]
@DatBoiWeep U did this for properties already right? we can close if so

**Comment by DatBoiWeep** [comment]
> @DatBoiWeep U did this for properties already right? we can close if so

Yes, good to close 👍🏼
