### ISSUE TITLE
Mirror Park tavern collision issue

### ISSUE THREAD

**Issue by ChangyBoi** [minipunch/usarealismrp-fxserver#1186]
Rudzik_Mirror_Bar has a door collision issue

**Comment by minipunch** [comment]
???

What needs to be done ?

**Comment by minipunch** [comment]
Sounds like we need @maxgestic  ?

**Comment by ChangyBoi** [comment]
Indeed we need @maxgestic pls fix collision at door

**Comment by maxgestic** [comment]
I'll have a look please send me the mlo resource name

**Comment by maxgestic** [comment]
I'll have a lookie

**Comment by Zeeroqt** [comment]
issue was resolved. mlo was removed
