### ISSUE TITLE
try fun looking orange picking script

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1190]
https://forum.cfx.re/t/paid-standalone-esx-collecting-oranges-ui-realistic-collection-system/4904117

**Comment by minipunch** [comment]
If ur looking at this and think u wanna try adding it 4 me

I will buy it 4 u just lmk

**Comment by maxgestic** [comment]
But why though 🤔

**Comment by minipunch** [comment]
Why NOT???

It's a way for civs to earn money lol

And I am sure some wouldn't mind / would like doing it

**Comment by Crownapple** [comment]
Done

**Comment by Savage912-Official** [comment]
Good to be closed
