### ISSUE TITLE
ability to rob players who have hands up

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1203]
so they don't ALWAYS need to be FULLY detained with rope

Maybe have the search interface close on the searcher if the victim puts their hands down at any time also

**Comment by Savage912-Official** [comment]
Currently working on this

**Comment by Savage912-Official** [comment]
Was done, just awaiting mini to check out the following things below and see if he can get them working properly.

- The being robbed player puts their hands down
- The being robbed player has enough distance between him and the robber

**Comment by minipunch** [comment]
finished this
