### ISSUE TITLE
try high phone

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1204]
new phone script, need to try it out and see how it is

looks cooler and has some nice features

should work fine with MySQL, no need to convert any DB stuff to couch

**Comment by minipunch** [comment]
@maxgestic this is me "assigning" you since I can't via the GH feature for whatever reason lol

**Comment by maxgestic** [comment]
It's cos I'm not longer a collaborator sadge but yea I'm working on it

**Comment by minipunch** [comment]
callbacks are a bitch on this 1

not working 

going to try npwd

**Comment by minipunch** [comment]
@maxgestic got this working so he is going to see if he can finalize this

**Comment by maxgestic** [comment]
Linking in progress PR https://github.com/minipunch/usarealismrp-fxserver/pull/1265

**Comment by minipunch** [comment]
So PR was merged but realized Twitter was p messed up due to phone_tweets db issues

Tried some stuff but none really fixed it well enough

So I am going to make sure it all works on my local server which has MySQL v5 and if it does I will try switching the live to use v5 instead of v8 and hopefully that's it

**Comment by minipunch** [comment]
or maybe use another data type that allows how it is now

**Comment by minipunch** [comment]
converting the long/medium text data types to varchars seems to be okay for now, don't really anticipate reach their limits so I think it will be ok

**Comment by minipunch** [comment]
yeah, looks good for now at least lol

Gonna make another PR n merge it
