### ISSUE TITLE
dumpster diving script

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1232]
to find random stuff in them

like stuff for crafting for example

**Comment by Savage912-Official** [comment]
Done in #1255, Just need to add more items, and the ability to find money tomorrow. Can be pushed now if wanted.

**Comment by minipunch** [comment]
This was merged

But there is an issue

- [ ] need to fix how searching one dumpster marks all dumpsters as searched

**Comment by minipunch** [comment]
added
