### ISSUE TITLE
try npwd

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1238]
"new phone who dis" phone to replace existing

it uses pma-voice so gotta make sure all that works still

but seems to work nice on my test server atm + it's open source

need to:
- [x] generate random phone numbers
- [x] make sure voice works good
- [x] make sure calling works good
- [x] try newest pma-voice
- [x] try new radio script (press 'u' to open UI)
- [x] change VOIP range toggle hotkey back to F2
- [x] make sure player gets assigned a random phone number properly
- [x] unload player when /swap is used
- [x] make sure 911, mechanic, uber, etc calls work
- [x] make sure group chats work
- [x] change radio interface open hotkey back to `SHIFT + F2`
- [x] change voip range toggle hotkey back to F2 from F11
- [x] change radio talk hotkey back to `CAPSLOCK`
- [ ] disable radio channel player list + frequency on HUD
- [ ] M menu VOIP range not connected
- [ ] adjust left side of HUD since VOIP stuff moved to right side
- [ ] no talking on radio when downed
- [ ] make sure police / ems have their private channels
- [x] run any manual setup on live server (like sql scripts basically or any building)
- [ ] final testing on public test server
- [ ] push

**Comment by minipunch** [comment]
matchmaker messaging says null when sending message

but still ok to push and can fix later

**Comment by minipunch** [comment]
manual steps involve running the `pe-core` resource sql file + the `npwd` resource sql file

**Comment by minipunch** [comment]
phone author said he is working on a fix for no message notifications atm

**Comment by minipunch** [comment]
probably going to use #1204 instead

**Comment by maxgestic** [comment]
Linking In progress PR https://github.com/minipunch/usarealismrp-fxserver/pull/1265
