### ISSUE TITLE
[Vehicle Boosting] Cars are "not spawning at all"

### ISSUE THREAD

**Issue by DatBoiWeep** [minipunch/usarealismrp-fxserver#1239]
Multiple players will start the contract and vehicle will not be present. 
Mentioned by @ChangyBoi 

- Assuming it might be that if another player is in range of the vehicle, it will de-spawn.

Will have to look into it

**Comment by DatBoiWeep** [comment]
@minipunch by any chance are there any script errors on the server end side with this?

**Comment by minipunch** [comment]
```
ERROR: @rahe-boosting/api/server.lua:31: attempt to index a nil value (local 'char')
player Chang (#1) dropped from the server!
```

is one

looks like it's cuz it's trying to get the char ID after the char object was removed (usa-characters removes it on player drop)

**Comment by minipunch** [comment]
looks like that's the only server error I can see at least

might be causing issues if something needs to be cleaned up but is failing due to that error

**Comment by minipunch** [comment]
does it work the first time they join the server at least ? before dropping and coming back in ?

**Comment by DatBoiWeep** [comment]
> does it work the first time they join the server at least ? before dropping and coming back in ?

going to test that real quick

**Comment by DatBoiWeep** [comment]
**Update**: Does not work first joining, nor if you come back.

On my test server, it's fine. At first, I thought it was an anti-cheese issue; it's not, still spawns vehicles with all of that on

**Comment by minipunch** [comment]
would prob have to be the first time u join the server PERIOD unless that is what u tried

but that's weird

**Comment by minipunch** [comment]
has it worked for anyone ?

**Comment by DatBoiWeep** [comment]
> has it worked for anyone ?

By the looks of it, no. There is also a part of the script that isn't running when I went on the live server. There should be a shop down by the Tuner Garage MLO. But the prompt doesn't even show. So my guess is that error probably stopping everything

**Comment by minipunch** [comment]
> > has it worked for anyone ?
> 
> By the looks of it, no. There is also a part of the script that isn't running when I went on the live server. There should be a shop down by the Tuner Garage MLO. But the prompt doesn't even show. So my guess is that error probably stopping everything

any F8 errors? I didn't see any other server errors

**Comment by DatBoiWeep** [comment]
> > > has it worked for anyone ?
> > 
> > 
> > By the looks of it, no. There is also a part of the script that isn't running when I went on the live server. There should be a shop down by the Tuner Garage MLO. But the prompt doesn't even show. So my guess is that error probably stopping everything
> 
> any F8 errors? I didn't see any other server errors

Nope, ped should spawn here but doesn't as well as a notification to purchase from the store as well
![image](https://user-images.githubusercontent.com/27328529/189501024-0d04e3db-debf-4825-b222-6b7913d2202d.png)

**Comment by DatBoiWeep** [comment]
This is the code that should be running, but its not. Not sure if the script loaded in properly, or if something is stopping it. Either way, should the script to create the ped isn't working, the shop should still show up regardless.

`-- Create Store Ped
Citizen.CreateThread(function()
    local spawn = 0
	while spawn == 0 do
		local playerCoords = GetEntityCoords(PlayerPedId(), false)
        local ped = {x = 128.85234069824, y = -3008.5986328125, z = 10.70343875885, heading = -230.0}
        if Vdist(ped.x, ped.y, ped.z, playerCoords.x, playerCoords.y, playerCoords.z) < 50 then
            local hash = -984709238
            RequestModel(hash)
            while not HasModelLoaded(hash) do
                RequestModel(hash)
                Wait(0)
            end
            local ped = CreatePed(4, hash, ped.x, ped.y, ped.z, ped.heading, false, true)
            SetEntityCanBeDamaged(ped,false)
            SetPedCanRagdollFromPlayerImpact(ped,false)
            TaskSetBlockingOfNonTemporaryEvents(ped,true)
            SetPedFleeAttributes(ped,0,0)
            SetPedCombatAttributes(ped,17,1)
            SetPedRandomComponentVariation(ped, true)
            TaskStartScenarioInPlace(ped, "WORLD_HUMAN_CLIPBOARD", 0, true)
        end
        spawn = spawn + 1
		Wait(1)
	end
end)`

**Comment by minipunch** [comment]
It says rahe-boosting was started in server log so it should all be loaded...

gonna see if it works for me rn

**Comment by minipunch** [comment]
also that code logic is a bit funny lol

think it might need adjusting

**Comment by minipunch** [comment]
Yeah the no ped spawning thing happens to me also even on my local test server

p sure that logic u posted needs some work

**Comment by DatBoiWeep** [comment]
> Yeah the no ped spawning thing happens to me also even on my local test server
> 
> 
> 
> p sure that logic u posted needs some work

Yeah. It was a quickie 💀 lol I'll fix that when I get home 🤣

**Comment by minipunch** [comment]
well I was able to reproduce this issue cause I couldn't find the declasse burrito it wanted me to find LOL

**Comment by minipunch** [comment]
![](https://i.imgur.com/m3C2n0E.png)

that's where it sent me but I can't find it

**Comment by DatBoiWeep** [comment]
> ![](https://i.imgur.com/m3C2n0E.png)
> 
> 
> 
> that's where it sent me but I can't find it

Hmm. That's heckin weird. I wonder if I have some files you don't. 🤔 

But everything should be the same

**Comment by DatBoiWeep** [comment]
I found an issue. It looks like the ox_lib wasn't called properly. Either `ox_lib` or the `oxmysql` is not running / working as intended.

![image](https://user-images.githubusercontent.com/27328529/189515495-3ac57349-cd4d-4b41-bf4f-f2e7de9b6973.png)

I know when I had this issue in my test server, nothing would work for the script itself, except for the UI

**Comment by DatBoiWeep** [comment]
This is what is said in support about this error.

![image](https://user-images.githubusercontent.com/27328529/189515587-b2774f50-3450-410d-a62b-2b1ba6e271fc.png)

**Comment by minipunch** [comment]
Ok I can look into that

**Comment by minipunch** [comment]
What 'cache' folder is he talking about in ox lib? I don't see any in the
official ox lib repo

**Comment by minipunch** [comment]
Oh nevermind, I do see it, and It looks like he's right lol

It's in ox_lib/resources/cache
