### ISSUE TITLE
add minigame for lockpicking cars

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1250]
right now it is just a boring progress bar with no challenge

**Comment by minipunch** [comment]
@Savage912-Official ?

**Comment by minipunch** [comment]
Didn't u already do this @Savage912-Official ?

**Comment by Savage912-Official** [comment]
Yep.

**Comment by Savage912-Official** [comment]
Guess I didn't mention this in the PR.
