### ISSUE TITLE
(Racing) Competitive Racing Issue 

### ISSUE THREAD

**Issue by DatBoiWeep** [minipunch/usarealismrp-fxserver#1272]
**Report**
Users are unable to find the location of where to join the race for competitive matches, even though it is being displayed on the tablet and the time it should begin. I reviewed a player's F8 logs for any errors and none were present. Is the server console returning any errors?

> So I've got a bunch of people interested in the racing scene here and we're trying to actually do these competition races but they always become "completed" hours before they were supposed to start.
> It was 3:30pm (in city) and we had two races that were supposed to start at around 9pm both just poof off the tablet and become complete 
![image](https://user-images.githubusercontent.com/27328529/190875275-3902aba9-2063-4dda-ad85-a2a7b942bc16.png)
![image](https://user-images.githubusercontent.com/27328529/190875277-43db6853-a168-4518-919e-6ed3113f8bcb.png)
> They all just became complete and poofed when they were set to run at 20:00+

**Comment by DatBoiWeep** [comment]
Might lower the number of users needed to join the race as a potential fix, if there are no server errors.

**Comment by DatBoiWeep** [comment]
Author of script said it could be a DB issue 🤷‍♂️

**Comment by minipunch** [comment]
No server errors

**Comment by DatBoiWeep** [comment]
> No server errors

Very well, thank you sir

**Comment by minipunch** [comment]
Has nobody else using this script reported this issue?

Idk why it would be just on our side for that

**Comment by DatBoiWeep** [comment]
> Has nobody else using this script reported this issue?
> 
> Idk why it would be just on our side for that

Not sure, so far only 2 users reported it through a DM with me. I'm going to get on the server today and hopefully see if I can join one of the comp matches that pop up.

**Comment by minipunch** [comment]
Sounds good

But I meant any other servers that use the script lol

**Comment by DatBoiWeep** [comment]
> Sounds good
> 
> But I meant any other servers that use the script lol

oh good point 💀

**Comment by DatBoiWeep** [comment]
It's based on the IRL time, not in-game time. LOL
