### ISSUE TITLE
try making hotkey to open inventory directly

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1273]
Like use register key map for the "i" key for inventory ?

should try n see if this works

**Comment by maxgestic** [comment]
I can do this and also make it so users can change the bind in the settings

**Comment by minipunch** [comment]
Ok

**Comment by maxgestic** [comment]
Done as per https://github.com/minipunch/usarealismrp-fxserver/commit/3661922523e82baa093619a8974c1fe30204ac84 
@minipunch close plz
