### ISSUE TITLE
phone stories app is using steam names

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1283]
should use char names instead like it did with the old phone

**Comment by minipunch** [comment]
@maxgestic Think u can look into this 4 me

**Comment by minipunch** [comment]
looks like it's easily configurable in the `cs-stories` resource config

**Comment by maxgestic** [comment]
Yea @minipunch I'll do this tonight

**Comment by maxgestic** [comment]
https://github.com/minipunch/usarealismrp-fxserver/pull/1294
