### ISSUE TITLE
phone: money receive/sends use steam name and have wrong currency symbol

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1302]
![](https://cdn.discordapp.com/attachments/297566457468944384/1022566944093769759/unknown.png)

@maxgestic think u can also take a look at fixing this 4 me 2 plz ?

- [ ] steam name should be char name
- [ ] currency symbol should be USD $

**Comment by maxgestic** [comment]
Name cant be changed its hard coded

**Comment by maxgestic** [comment]
I can remove it though, so its just the ID, @minipunch if you want?

**Comment by minipunch** [comment]
Yes plz do

**Comment by minipunch** [comment]
I want to request money from people without them knowing it's THE MINIPUNCH

**Comment by minipunch** [comment]
Also don't wanna change my steam name lol

**Comment by minipunch** [comment]
adjusted
