### ISSUE TITLE
spawn vehicles server sided to replace client side spawning of vehicles

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1306]
see: https://github.com/citizenfx/fivem/commit/1e266a2ca5c04eb96c090de67508a3475d35d6da or CreateAutombile native (i think has to be invoked manually)

can be used to fix disappearing cars when going far away from them p sure if we spawn them on the server instead of client

like when they pull out of the garage, use this native instead of the client CreateVehicle native

**Comment by maxgestic** [comment]
![image](https://user-images.githubusercontent.com/3323241/199337119-4f55c97b-0a16-48c2-a7ec-0526671fc26a.png)
Doesnt work

**Comment by minipunch** [comment]
Hm make sure u r using the latest server artifact

Also make sure we are using the latest 'resource manifest' version, so check ``_resource.lua` or `fxmanifest` of `es_admin`, whatever it is and make sure it using the most up to date manifest/game script version

**Comment by minipunch** [comment]
Cause I know it is a relatively newly added native

**Comment by minipunch** [comment]
Or better yet if that doesn't work still, try the p much equivalent `CreateAutomobile` server side native and see if that one works

**Comment by minipunch** [comment]
this is a duplicate issue
