### ISSUE TITLE
hitting ESC toggles 4 way blinkers when using phone

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1315]
for some reason seems like it only works when the phone is open tho

**Comment by maxgestic** [comment]
I cant figure out what could cause this tbh

**Comment by minipunch** [comment]
> 

We have a script / some code somewhere that makes `-` left turn signal and `=` right turn signal and finally `backspace` as the hazards

I forget where it is exactly though, would have to find it

**Comment by minipunch** [comment]
new phone might fix dis
