### ISSUE TITLE
'use'ing phone does not open interface anymore

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1332]
forced to use hotkey

should be able to 'use' the phone item in the inv to open the phone also

@maxgestic

**Comment by maxgestic** [comment]
Done https://github.com/minipunch/usarealismrp-fxserver/pull/1338

**Comment by minipunch** [comment]
Don't forget to put "closes #issue-number" in the PR and it should auto close the issue too
