### ISSUE TITLE
cannot message a mechanic?

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1333]
does sending a text to the built in "Mechanic" contact not send it to all mechanics like the old phone would?

if not then we should update that

@maxgestic ?

**Comment by maxgestic** [comment]
It should do? It should phone all mechanics when you phone and text all mechanics when you text the contact

**Comment by minipunch** [comment]
![](https://i.imgur.com/INGtYu8.png)

I sent all those messages after doing `/setjob mechanic` and still nothing popped up in chat

**Comment by minipunch** [comment]
Also tried on local server and same issue there

Thought I tested this before merging but I guess not ?

**Comment by minipunch** [comment]
Think the same thing applies to the taxi job also

**Comment by maxgestic** [comment]
I do not believe you can message your own job, I'll test it but I'm pretty sure it doesn't work that way

**Comment by minipunch** [comment]
Hm ok, yeah we should try to confirm

fyi if u didn't know just make a new shortcut to fivem.exe and pass the `-cl2` flag to start a 'second client' easily for testing with 'another person' easily if nobody else is immediately available

**Comment by minipunch** [comment]
I just tried this and it works like u said it would

so I guess this ain't an issue really
