### ISSUE TITLE
new gabz maps

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1335]
for sept release to try out

need to download and upload to the repo for others to try out and add if good

**Comment by minipunch** [comment]
just downloaded the new list of maps and still can't find the new ones because mr gabz somehow magically expects his customers to know that information I guess

**Comment by minipunch** [comment]
would LOVE if SOMEONE would share that so I knew what to add

**Comment by DatBoiWeep** [comment]
I believe the maps should be named
- Altruists
- Aztecas
- Ballas
- Families
- Marabunta
- Triads
- Vagos

**Comment by minipunch** [comment]
Well they are never named exactly that, but hopefully it includes those names at least

**Comment by minipunch** [comment]
can also look into paying Gabz more money for eternity to get the better doors and audio stuff

**Comment by DatBoiWeep** [comment]
> Well they are never named exactly that, but hopefully it includes those names somewhere at least

Oh. Wack, tell him give names or riot

**Comment by minipunch** [comment]
These are the only ones I have

![](https://i.imgur.com/LU97zr2.png)

Did I not receive the update or smth??? @ChangyBoi @DatBoiWeep

**Comment by ChangyBoi** [comment]
@minipunch did you download the cfx-gabz-package3

**Comment by minipunch** [comment]
3?????????

I don't have any `cfx-gabz-package3`.. only 1 and 2 as shown above...

**Comment by ChangyBoi** [comment]
> 3?????????
> 
> I don't have any `cfx-gabz-package3`.. only 1 and 2 as shown above...

yeah there should be a package 3 which includes the new ones

**Comment by ChangyBoi** [comment]
Go in Gabz's discord and do this follow these steps

Our september update includes a new cfx-gabz-package3 . **If you're missing this package on your keymaster, simply put your cfx username in #grants. I'll manually fix it as soon as possible** (yes you may have to wait).

**Comment by minipunch** [comment]
Nice thanks

Maps pushed @chang'

**Comment by minipunch** [comment]
these got added
