### ISSUE TITLE
add chance for GSW call at hospital

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1367]
instead of being 100% of time

is it currently 100% of time @DatBoiWeep  ? since u worked on it last

**Comment by DatBoiWeep** [comment]
Yes, there's no chance in there

**Comment by DatBoiWeep** [comment]
But I could probably add a `math.random()` in there and give it a low-medium chance

**Comment by minipunch** [comment]
> But I could probably add a `math.random()` in there and give it a low-medium chance

![](https://media.tenor.com/cJ9V22mZIG0AAAAS/do-it-just-do-it.gif)
