### ISSUE TITLE
Rahe Hacking Device issue

### ISSUE THREAD

**Issue by DatBoiWeep** [minipunch/usarealismrp-fxserver#1369]
After testing out some changes for `rahe-boosting` I came across an issue where the hacking menu didn't show up. Also tested this on the live server to see if it was just my issue. Which thou was not.

**Fix**
@minipunch you just need to re-build the file in `resources\rahe-hackingdevice\web\package.json` and it should be all good

**Comment by DatBoiWeep** [comment]
If needed, I can just make a PR for my `package-lock.json` file

**Comment by minipunch** [comment]
Since the `node_modules` folder (the folder produced by 'building') is not tracked by git I will have to do it manually for any source code changes to go into place unfortunately but that's not too big of a deal

**Comment by minipunch** [comment]
But did you push any changes here? Shouldn't I see a PR with ur 'fixes' ?

**Comment by DatBoiWeep** [comment]
Oh I don't have changes yet. But I'll work on them now LOL

**Comment by DatBoiWeep** [comment]
It was more changes over "fixes". The only fixing was compiling the hacking-device thingy

**Comment by minipunch** [comment]
So ur saying

1) I need to build the rahe-hackingdevice script
and 2) ur gonna make a PR soon to complete it?

**Comment by DatBoiWeep** [comment]
> So ur saying:
> 
>     1. I need to build the rahe-hackingdevice script
> 
>     2. and ur gonna make a PR soon to complete the rest?

Yes. Pretty much just need to build the `rahe-hackingdevice` script. And I will work on making some changes for a future PR :)

**Comment by minipunch** [comment]
Ok

And when u say 'rebuild

U mean just `npm install` ??

**Comment by minipunch** [comment]
Oh looks like it's `yarn build`

**Comment by DatBoiWeep** [comment]
Fixed by @minipunch and #1395
