### ISSUE TITLE
try roller skating script

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1433]
https://forum.cfx.re/t/update-roller-ice-skating-script-standalone/4791919

**Comment by minipunch** [comment]
@Crownapple said he would try this

**Comment by minipunch** [comment]
It's not letting me buy it for some reason lol I think FiveM is still having some issues there

**Comment by minipunch** [comment]
But remind me in a bit if I don't get it to u

**Comment by maxgestic** [comment]
I will be looking at this
