### ISSUE TITLE
prevent plasma gun from being taken when going to jail

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1494]
happened to someone who bought one

not sure if it was the /seize command used by an LEO that did it or if the prison took it automatically, but the former seems more likely

**Comment by Crownapple** [comment]
The plasma gun is marked as a weapon so if a person enters with a gun is auto takes it. But im sure the /seize does it as well

**Comment by minipunch** [comment]
fixed
