### ISSUE TITLE
Ability to change the key bind for riding cow 

### ISSUE THREAD

**Issue by Rezitoo** [minipunch/usarealismrp-fxserver#1541]
When in the farm **E** is the key bind to do anything with the animals, when dealing with cows you are constantly getting on them and it causes them to freak out. Would be nice if you could change the key bind for riding them. 

https://streamable.com/mmgcrp

**Comment by Savage912-Official** [comment]
Submitted this change, The default Key is still E but can be changed in the FiveM Keybind Settings.
