### ISSUE TITLE
Neon Lights not staying on cars

### ISSUE THREAD

**Issue by Urbaniized** [minipunch/usarealismrp-fxserver#1565]
Neon lights will be bought from LS customs and when the vehicle is put in the garage and taken back out, the neon lights will disappear.

https://usarrp.gg/forums/topic/1332-underglow

Rezito — Today at 12:42 AM
Mini that bug, it happens when you go into a bennys or a ls customs then put the car in your garage and pull it back out. You won't have underglow and a random car(s) in your garage will have it

**Comment by minipunch** [comment]
would be good to set up some debug info for critical events like saving veh data, pulling from garage, etc to try to maybe log when something looks wrong or changes so they player can provide some more info when it occurs on live

**Comment by minipunch** [comment]
because it seems either like 1) a race condition somehow or 2) some steps that I haven't been able to reproduce yet

**Comment by Urbaniized** [comment]
@Rezitoo Said that the neons stay as long as you don't take the vehicle back into an LS customs. Once you go into an LS customs and come back out then it will disappear

**Comment by Rezitoo** [comment]
Basically I believe I have narrowed it down to the fact when you purchase underglow it takes the money but doesn't save the purchase so then when you back into a customs you have to rebuy it because then when you pull the car out of the garage and it loads the mods there is no underglow since it wasn't purchased

**Comment by Urbaniized** [comment]
Apparently extras act the same way. They do not save on the vehicles

**Comment by maxgestic** [comment]
I will investigate

**Comment by maxgestic** [comment]
Its weird i tried everything and cant reproduce

**Comment by Urbaniized** [comment]
You are not the only one, I was not able to reproduce it on my server but it happened to me on live. I lost my neons on live, I went and purchased them on a separate car and they also disappeared

**Comment by Rezitoo** [comment]
When you purchase an engine upgrade for example, there is a small purchased icon that shows up where the price was, but when purchasing underglow or liveries that doesn't show up and both of those are things we are having issues with disappearing after you re-enter any customs and then put the car in a garage then pull it back out

**Comment by minipunch** [comment]
> When you purchase an engine upgrade for example, there is a small purchased icon that shows up where the price was, but when purchasing underglow or liveries that doesn't show up and both of those are things we are having issues with disappearing after you re-enter any customs and then put the car in a garage then pull it back out

That's a good find right there

**Comment by minipunch** [comment]
What are the categories in the LSC that we have this issue with?

It seems to be limited to a subset of categories like @Rezitoo said above

Is it just liveries, extras, and underglow? everything else works fine?

**Comment by Rezitoo** [comment]
Hmm interesting, it has to be something database then because it is just strange. HAs me completely stumpted

**Comment by Urbaniized** [comment]
I did some testing, the neon upgrade gets lost whenever the car is put in a garage and taken back out.

I used the following command to see when it gets lost;

`
RegisterCommand("getneon", function(source, args, rawCommand)
  local veh = GetVehiclePedIsIn(PlayerPedId())
  local value = IsVehicleNeonLightEnabled(veh)
  print(value)
end)
`

Found out it only gets lost when the car is stored away. I looked into `usa_garage` and found the function `applyCustomizations` which traced back to `lscustoms` resource.

After some testing, I changed a couple of lines in that function and that seems to have fixed the issue on my server. Maybe someone else can try it to confirm?

https://github.com/minipunch/usarealismrp-fxserver/pull/1650

**Comment by minipunch** [comment]
Don't think that's gonna help

This however looks far more promising: https://github.com/minipunch/usarealismrp-fxserver/issues/1623#issue-1499403811

**Comment by minipunch** [comment]
Didn't mean to close yet, we should give it some more time and see if people lose underglow still or not after that update

**Comment by Rezitoo** [comment]
So basically it lasted two days and then it went away

**Comment by minipunch** [comment]
Lol this happened to me with my low grips just now on live

just bought a new car, put low grips on, then like I think I just used the ls customs again or something and it went away the same day I think...

**Comment by minipunch** [comment]
#1669 should fix this when complete though p sure
