### ISSUE TITLE
push new gabz arena map stuff

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1595]
for @DatBoiWeep n company to try

**Comment by Savage912-Official** [comment]
Send it over before you push so I can setup basketball script with it.

**Comment by minipunch** [comment]
I pushed it

So maybe @Savage912-Official  and @DatBoiWeep can work 2gether to get it in with some interior type we can decide on for now and set up the basketball stuff

**Comment by DatBoiWeep** [comment]
@Savage912-Official I changed the Maze Bank Arena to the BasketBall Court, so you should be good to pull the map repo and add the basketball courts

**Comment by Savage912-Official** [comment]
> @Savage912-Official I changed the Maze Bank Arena to the BasketBall Court, so you should be good to pull the map repo and add the basketball courts

I don't got access :(

**Comment by minipunch** [comment]
> > @Savage912-Official I changed the Maze Bank Arena to the BasketBall Court, so you should be good to pull the map repo and add the basketball courts
> 
> I don't got access :(

I got u access @Savage912-Official

**Comment by Savage912-Official** [comment]
Alright Ill start working on it in a bit
