### ISSUE TITLE
F9 Issues

### ISSUE THREAD

**Issue by maxgestic** [minipunch/usarealismrp-fxserver#1602]
`if u flip ur car and f9, a+d wiggle lets u flip ur car`
`if you alt w crouch then f9 ur walk style`

**Comment by minipunch** [comment]
> "if you alt w crouch then f9 ur walk style" 

what does this mean lol

**Comment by maxgestic** [comment]
So if you crouch, then change your walk style, it bugs it out where every time you aim it insta crouches you and when you stop aiming your char stands again
