### ISSUE TITLE
load screen radio stopped working?

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1663]
seems like there is no music during load screen now for some reason

**Comment by minipunch** [comment]
hm yeah seems like maybe fivem updated chromium and now auto play doesn't work?

seems like it is requiring the user to click or do some gesture to start playing as the auto policy from 2017 states

**Comment by minipunch** [comment]
maybe we can try playing just a smaller mp3 file on autoplay

or is there literally just no way to auto play audio now ?

**Comment by Savage912-Official** [comment]
Can also be xlosed
