### ISSUE TITLE
3rd eye job restricted actions

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1715]
cuffing, frisking, impound, bandage, etc for LEO/EMS actions

tow, repair, etc for mechanics

heal for doctors (or w/e the commands are)

**Comment by minipunch** [comment]
although the more I think about it the more I think maybe they don't need to be 'job restricted' and can just rely on items instead for the most part?

**Comment by minipunch** [comment]
I guess for now if it is simple enough to do job restricted stuff we can do it that way for now

**Comment by Khajit71** [comment]
IMO would be ideal for not only jobs, but also day to day props/items, like filling up the car with gas for example, or searching dumpsters, opening a buying menu at the 24/7 by looking at the clerk OR on the register, etc

**Comment by minipunch** [comment]
Yeah for sure, but right now things that are already easily interactable (like by pressing E when prompted) are lower prio

**Comment by minipunch** [comment]
[3151c16](https://github.com/minipunch/usarealismrp-fxserver/commit/3151c164b8d231deab3606f4612f60d8963df2fe)
