### ISSUE TITLE
train script texture needs optimized

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1717]
> "Asset trains/freightcont.ytd uses 72.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 
'city bug' or 'streaming isn't great')."

shows red in console on startup with that msh

**Comment by minipunch** [comment]
@maxgestic Can u look into this since this was introduced in ur train stuff plz

**Comment by minipunch** [comment]
https://forum.cfx.re/t/how-to-optimize-texture-size-fixing-oversized-assets-bring-any-texture-dictionary-under-16-mb-physical-memory/1764640

**Comment by maxgestic** [comment]
OK fix ed it by removing all the models we dont actually use
![image](https://user-images.githubusercontent.com/3323241/215293021-1372884e-f1ec-433d-89a7-b8b6107275c9.png)
