### ISSUE TITLE
allow players to 'fight back' when being cuffed

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1727]
like some mini game that appears where it gives them a chance to break free

ideally it would be like COP vs. CRIM and whoever wins the mini game wins the cuffing battle

but if not that then at least letting the crim do some mini game for a chance to prevent the cuff would work for now

**Comment by minipunch** [comment]
prob just use the same one we use for hotwiring for now to be easy

**Comment by Khajit71** [comment]
would be best to have to press just once tho in the minigame, otherwise cops would have time to put u in the cop car, search, or other stuff

**Comment by minipunch** [comment]
> 

https://cdn.discordapp.com/attachments/984831583909445693/1067600436711927829/FiveM_by_Cfx.re_-_Savages_Development_Server_2023-01-24_19-18-38.mp4

**Comment by minipunch** [comment]
> would be best to have to press just once tho in the minigame, otherwise cops would have time to put u in the cop car, search, or other stuff

https://cdn.discordapp.com/attachments/984831583909445693/1067600436711927829/FiveM_by_Cfx.re_-_Savages_Development_Server_2023-01-24_19-18-38.mp4

**Comment by maxgestic** [comment]
I think those three is a good one, means its not super easy but also not too hard

**Comment by minipunch** [comment]
Yeah, maybe just a bit harder (aka faster moving) also I think

But p good other than that I think

**Comment by Savage912-Official** [comment]
> > I think those three is a good one, means its not super easy but also not too hard
> 
> Yeah, maybe just a bit harder (aka faster moving) also I think
> 
> But p good other than that I think

Yeah we can always speed it up if you want.
