### ISSUE TITLE
force LEOs to actually transport prisoners realistically

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1729]
instead of futuristically making them disappear and then appear in another place suddenly

prob best way for now would be to just do a distance check whenever someone submits a jail form

transports make for good RP and is much more realistic and fun

**Comment by maxgestic** [comment]
Issue is no Corrections officers are online ever cos it's boring and normal officers won't wanna drive people all the way to sandy cos that's not really what cop RP is meant to be

**Comment by minipunch** [comment]
> "not really what cop RP is meant to be"

disagree

**Comment by minipunch** [comment]
also not just about the cops

civs get good RP from it too

**Comment by minipunch** [comment]
and the idea is ultimately it brings more on because people enjoy doing jobs that need to be filled
