### ISSUE TITLE
pickle construction job script

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1828]
https://forum.cfx.re/t/pickles-construction-structures-vehicles-lifts-10-structures-and-more/5013157

**Comment by Zeeroqt** [comment]
this link is the farming one btw

**Comment by minipunch** [comment]
fixed ty

**Comment by DatBoiWeep** [comment]
This is actually pretty 🔥 ngl

**Comment by minipunch** [comment]
finished this up, it is pretty fire

just need testing group to try it out + make sure it pays good enough

**Comment by minipunch** [comment]
testing was good

just need to:
- [ ] make sure pay is good still after raising it
- [ ] try to figure out why certain build points don't give u a prompt
