### ISSUE TITLE
Slash Tires 

### ISSUE THREAD

**Issue by Rezitoo** [minipunch/usarealismrp-fxserver#1857]
Give people the ability whilst wielding a knife to go up to parked cars and slash the tire(s).  

- [x] Alert 911 of tire(s) being Slashed
- [x] Allow Emergency vehicles tire(s) to be slashed
- [ ] Possibly give a cool down after 4 slashes 
- [x] Add a chance of "Missing" the slash

**Comment by Rezitoo** [comment]
Still working on adding it to the 3rd eye

**Comment by Savage912-Official** [comment]
#1980

**Comment by Rezitoo** [comment]
Merged
