### ISSUE TITLE
way to toggle staff chat message visibility

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1885]
so u can stream and keep staff chats pvt

**Comment by Savage912-Official** [comment]
Does /togglestaff not work?

**Comment by minipunch** [comment]
Not sure actually but for some reason I don't think it popped up in the chat suggestions when I did "/toggle" lol

someone should confirm and we can close this if it does

**Comment by Savage912-Official** [comment]
I’ll check it out in the morning

**Comment by Savage912-Official** [comment]
It seems to be working for me. Also tested and it seems to be working with muting staff chat and notifications.

https://i.imgur.com/NvJxbUP.png

**Comment by minipunch** [comment]
nice, yeah it does

guess I just missed cause I couldn't remember the command and didn't see it in suggestions
