### ISSUE TITLE
Joint Updates

### ISSUE THREAD

**Issue by Savage912-Official** [minipunch/usarealismrp-fxserver#1891]
https://usarrp.gg/forums/topic/1856-high-effect/

I’ll change it tomorrow

**Comment by Zeeroqt** [comment]
Possibly a way to auto cancel smoking a joint if u are already maxed armor 80% from smoking so it’s not just wasting and a way to cancel smoking a joint also 👀

**Comment by Zeeroqt** [comment]
Crims would really like that😶‍🌫️
