### ISSUE TITLE
3rd eye options for ATMs

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1895]
- [x] use
- [x] hack

where `hack` is to initiate @maxgestic 's ATM hacking stuff (I guess it would be to simulate as if they 'used' a drill near an atm, right?)

and `use` just opens the use as if they pressed E

**Comment by maxgestic** [comment]
Well yea I'd probs do drill instead of hack as an option

**Comment by minipunch** [comment]
but someone who is new wouldn't know what to do after 'drill' ing? unless it prompts u then

**Comment by minipunch** [comment]
done
