### ISSUE TITLE
vehicles to add new drive by animation to

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1920]
- [ ] durango
- [ ] one of the mercedes'
- [ ] bravado buffalo (GTA V charger)

**Comment by minipunch** [comment]
@Urbaniized  ^ por favor

**Comment by minipunch** [comment]
Maybe if we just can get a handling entry in for the native car then we'll be able to modify it's layout as we do with the others?

See if that works n lmk plz

**Comment by Urbaniized** [comment]
Yeah, I will try that. we already have the vehicle.meta in the assets folder for the native cars

**Comment by Urbaniized** [comment]
Confirmed, it will not work with base GTA cars
