### ISSUE TITLE
.50 cal pistol 'poofing' issue

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1922]
see: https://discord.com/channels/297566457468944384/363082636505382912/1084889000973701182

multiple people have reported this happening, and there is a clip of it

1) gun disappears for some reason on reload in arcade mode
2) also looks like the .50 cal is accepting .45 cal bullets incorrectly ?

**Comment by ChangyBoi** [comment]
It didnt actually take my bullets

**Comment by minipunch** [comment]
also https://usarrp.gg/forums/topic/1742-50-cal-poofing/#comment-5211
