### ISSUE TITLE
update hotkey cheat sheet

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#1970]
- [x] add I for inventory
- [x] remove C for toggling safety since that no longer applies
- [x] then update #start-here in Discord and in the in game guidebook

**Comment by minipunch** [comment]
@Rezitoo wanna do this ?? I can send u the PSD if u can't find it but I also think it is listed in one of the staff chats

**Comment by Rezitoo** [comment]
> @Rezitoo wanna do this ?? I can send u the PSD if u can't find it but I also think it is listed in one of the staff chats

Yeah I can knock that out

**Comment by minipunch** [comment]
Sent it

**Comment by minipunch** [comment]
@Rezitoo can u paste the link to the chat msg in our DMs that with the updated file 4 me plz here

**Comment by minipunch** [comment]
done
