### ISSUE TITLE
load screen links not copying to clipboard

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#2082]
as it says they do and should

**Comment by minipunch** [comment]
@Crownapple

**Comment by Crownapple** [comment]
I will look into it tomorrow

**Comment by Savage912-Official** [comment]
I took a look at this @Crownapple, all you have to do is go into the main.js of the loading screen, goto line 84 and uncomment `copyToClipboard(link)`. It seems it was commented out.

**Comment by minipunch** [comment]
Nice @Savage912-Official, that was it indeed
