### ISSUE TITLE
see if ox-target works on downed people

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#2085]
since meta target doesn't atm

https://overextended.github.io/docs/ox_target/Usage/Globals

**Comment by Savage912-Official** [comment]
It should from what ive read

**Comment by minipunch** [comment]
we should try it to confirm

**Comment by minipunch** [comment]
still doesn't

it's definitely cause of the way we handle deaths (namely using the `FreezeEntityPosition` entity) that seems to make it not detect

**Comment by minipunch** [comment]
would need to find a way to not use that native in `usa_deaths` for it to work most likely
