### ISSUE TITLE
try out this 'fps booster' script

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#2090]
https://github.com/alp1x/um-fpsbooster

not sure if it will cause any issues or not but seems somewhat legit so could use some testing to try out at least

**Comment by Rezitoo** [comment]
@minipunch So I added this to my test server and got a few errors, looks like it is designed to have an interface that uses ESX but when using it through F8 it seemed to give me a 20-40 fps boost, While giving the error it still seemed to work for me

**Comment by minipunch** [comment]
> @minipunch So I added this to my test server and got a few errors, looks like it is designed to have an interface that uses ESX but when using it through F8 it seemed to give me a 20-40 fps boost, While giving the error it still seemed to work for me

Did u notice any weird effects? visual or gameplay?

**Comment by Rezitoo** [comment]
> > @minipunch So I added this to my test server and got a few errors, looks like it is designed to have an interface that uses ESX but when using it through F8 it seemed to give me a 20-40 fps boost, While giving the error it still seemed to work for me
> 
> Did u notice any weird effects? visual or gameplay?

Well It definitely makes the game look different. From what I read it looks like depending on which version you select it disables certain graphic options to increase FPS. I think if someone really wants to boost the fps it is worth it, nothing game breaking  from what I saw

**Comment by Rezitoo** [comment]
There is a command you type in to F8 with three different settings, _ulow_ _low_ _medium_ each having a stronger effect then the last on fps. Could be worth added even with the error

**Comment by maxgestic** [comment]
Please only add if there is a way to fully disable jt
