### ISSUE TITLE
Please can you make this Public Repo Private

### ISSUE THREAD

**Issue by McKlean** [minipunch/usarealismrp-fxserver#2099]
Hey Guys,

I'm not sure you are aware but your Repo is public meaning this can cause paid scripts you have being leaked, if you could please make this a private repo so developer's hard work doesn't get leaked. Much would be appreciated

**Comment by minipunch** [comment]
If you're the author of one of the scripts and want it private let us know

**Comment by McKlean** [comment]
I'm not the author but I know a few authors whose stuff your publicly and illegally showing...
Be a decent person and either make your repo private or pull out all scripts from creators you have not got permission to use.

You have no right to have these peoples code on show
