### ISSUE TITLE
Not able to sell paintings from art heist

### ISSUE THREAD

**Issue by Khajit71** [minipunch/usarealismrp-fxserver#2202]
People have been saying they can't sell paintings from art heist.

This is because if you rob it 2 times without relogging, it won't let you, it glitches. It might also randomly glitch, but doubt it. Either way, you have to relog after selling them the first time. Confirmed by a guy that robs it often

**Comment by minipunch** [comment]
might be the cooldown thing

added a help message for more info to see if that really is the issue
