### ISSUE TITLE
limit robbery reward when no cops on

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#2323]
rn it gives the same amount regardless of any cops online or not

should give a bit less if no cops online

**Comment by GordoHockey4** [comment]
If I change the policeNeededForBonus = 3    ---->   policeNeededForBonus = 0     AND THEN changed  bonus = math.floor(reward * 0.40)   ---->  to have a negative 0.40 or something of the sorts...would that work???

**Comment by GordoHockey4** [comment]
OR would that just make anytime there is 0 to however many cops online...a deduction in robbery earnings

**Comment by GordoHockey4** [comment]
Attempted to add a bonus if cops are online...we can reduce values if needed to make it lower when cops offline...again all just an attempt...I am very new at this lol and have a LOT to learn

**Comment by minipunch** [comment]
[716fb1d](https://github.com/minipunch/usarealismrp-fxserver/commit/716fb1de7ee3e8cd2c732f9d28853019465183e5)
