### ISSUE TITLE
A way to mark weapons as stolen

### ISSUE THREAD

**Issue by maxgestic** [minipunch/usarealismrp-fxserver#646]
maybe see a list of firearms a person owns to find out serials by purchase date if they dont know the serial of the weapon and then a button on the weapon search tab of the MDT like "Mark as Stolen" to mark a weapon as being stolen since PD bolo's only last a week now and there is no real good way to mark down stolen weapons now

**Comment by minipunch** [comment]
I think the newly added 'weapon notes' serves this purpose pretty well so we can close this now
