### ISSUE TITLE
fix speaker dupe bug

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#838]
> "its so easy to dupe them two people have to interact with the speaker and both have to click pick up and thats it you get duped speakers."

**Comment by NotCamSlice** [comment]
add a check. once player one is interacting with said item, others players can not interact with player one item. I'll fork over the repo this evening and debug this more.

**Comment by minipunch** [comment]
Should be easy enough to not pick up if already picked up by someone, little if statement

So 2 people can still open the interaction menu at once but should still prevent duping

Was gonna look at fixing this 2 soon

**Comment by minipunch** [comment]
patched this, see the relevant commit for how
