### ISSUE TITLE
enforce newer game build

### ISSUE THREAD

**Issue by minipunch** [minipunch/usarealismrp-fxserver#984]
currently using tuner dlc

wat's the newest??

maybe that will fix the random teleporting since not sure what else might be the deal there

**Comment by DatBoiWeep** [comment]
https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build

The latest build seems to be 
- 2612 | mpg9ec

**Comment by minipunch** [comment]
Idk wtf that an 'mpg9ec' even is or if it's stable enough to use

The next one b4 that might be a safer bet in the mean time

**Comment by DatBoiWeep** [comment]
LOL True. Thats probably going to be the safe bet to test out and stuff

**Comment by minipunch** [comment]
done
